### ISSUE TITLE
500 Internal error при создании спринта

### ISSUE THREAD

**Issue by GrafEHOT** [256MbTeam/Redmine-Scrumbler#102]
Привет. Стоит Redmine v 2.3.3, последняя версия Вашего прекрасного плагина, Ruby v 1.9.1. К сожалению после установки не работает одна из самых важных частей плагина, а именно отображение спринтов. При создании новой версии проекта автоматически не добавляется спринт во вкладку скрамблер. При нажатии кнопки "показать все спринты" выдает 500 Internal error, в настройках при нажатии на необходимую версию- тоже. Доступ ко всему предоставлен, установка и миграция плагина прошла успешно. Параллельно с Вашим плагином стоит Redmine Backlogs. Может ли как-то конфликтовать и если да, то подскажите пути решения. Также хотелось услышать от Вас решение данной проблемы. Обыскал весь хаб, но именно связанное с моей проблемой не нашел (может я слепой, не знаю). Очень надеюсь на Вашу скорую помощь.
При переходе на спринт:

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error. 
С уважением, Константин.
В логах указанна ошибка : 

  Processing by ScrumblerController#index as HTML
  Parameters: {"show_all"=>"", "project_id"=>"scrumbler-test"}
  Current user: KRepin (id=89)
  Rendered plugins/redmine_scrumbler/app/views/scrumbler/index.html.erb within layouts/base (169.8ms)
Completed 500 Internal Server Error in 189ms

ActionView::Template::Error (undefined method `remote_function' for #<#<Class:0x00000006839d38>:0x00000006b85ca8>):
    34:                         :controller => :scrumbler,
    35:                         :action => :sprint,
    36:                         :project_id => @project
    37:                         }, :with => "'sprint_id='+value")
    38:                         }%>
    39:                 </p>
    40:                 <p>
  plugins/redmine_scrumbler/app/views/scrumbler/index.html.erb:37:in`_plugins_redmine_scrumbler_app_views_scrumbler_index_html_erb___80248661326645626_41983720'
  actionpack (3.2.13) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.13) lib/active_support/notifications.rb:125:in`instrument'
  actionpack (3.2.13) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.13) lib/action_view/renderer/template_renderer.rb:47:in`block (2 levels) in render_template'
  actionpack (3.2.13) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in`block in instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in`instrument'

**Comment by box789** [comment]
такая же беда
