### ISSUE TITLE
Issue Migrating plugin to Chiliproject 3.2.2

### ISSUE THREAD

**Issue by jdaily** [256MbTeam/Redmine-Scrumbler#83]
Im running ruby1.9.3 and rubygems 1.8.11 on Ubuntu 12.04 with CP 3.2.2. 

Error message:
undefined method `application' for Rails:Module

Exception class:
NoMethodError

Application root:
/var/www/chiliproject

Backtrace:
# File    Line    Location

0   /var/www/chiliproject/vendor/plugins/redmine_scrumbler/init.rb  22  in `block in evaluate_init_rb'
1   /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb   158 in`eval'
2   /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb   158 in `block in evaluate_init_rb'
3   /var/lib/gems/1.9.1/gems/activesupport-2.3.14/lib/active_support/core_ext/kernel/reporting.rb   11  in`silence_warnings'
4   /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb   154 in `evaluate_init_rb'
5   /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/rails/plugin.rb   48  in`load'
6   /var/www/chiliproject/vendor/plugins/engines/lib/engines/plugin.rb  45  in `load'
7   /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/rails/plugin/loader.rb    38  in`block in load_plugins'
8   /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/rails/plugin/loader.rb    37  in `each'
9   /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/rails/plugin/loader.rb    37  in`load_plugins'
10  /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/initializer.rb    369 in `load_plugins'
11  /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/initializer.rb    165 in`process'
12  /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/initializer.rb    113 in `run'
13  /var/www/chiliproject/config/environment.rb 45  in`'
14  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb    222 in `require'
15  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb    222 in`preload_application'
16  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb    181 in `block in initialize_server'
17  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/utils.rb    572 in`report_app_init_status'
18  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb    174 in `initialize_server'
19  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb  204 in`start_synchronously'
20  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb  180 in `start'
21  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/classic_rails/application_spawner.rb    149 in`start'
22  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb    219 in `block (2 levels) in spawn_rails_application'
23  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/abstract_server_collection.rb   132 in`lookup_or_add'
24  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb    214 in `block in spawn_rails_application'
25  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/abstract_server_collection.rb   82  in`block in synchronize'
26      prelude>    10:in `synchronize'
27  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/abstract_server_collection.rb   79  in`synchronize'
28  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb    213 in `spawn_rails_application'
29  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb    132 in`spawn_application'
30  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/spawn_manager.rb    275 in `handle_spawn_application'
31  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb  357 in`server_main_loop'
32  /var/lib/gems/1.9.1/gems/passenger-3.0.13/lib/phusion_passenger/abstract_server.rb  206 in `start_synchronously'
33  /var/lib/gems/1.9.1/gems/passenger-3.0.13/helper-scripts/passenger-spawn-server 99  in`'

Here is my migration rake trace

bundle exec rake db:migrate:plugin NAME=redmine_scrumbler --trace

DEPRECATION WARNING: Rake tasks in vendor/plugins/redmine_git_hosting/tasks, vendor/plugins/redmine_git_hosting/tasks, and vendor/plugins/redmine_git_hosting/tasks are deprecated. Use lib/tasks instead. (called from <top (required)> at /var/lib/gems/1.9.1/gems/rails-2.3.14/lib/tasks/rails.rb:10)
*\* Invoke db:migrate:plugin (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
rake aborted!
Access denied for user 'root'@'localhost' (using password: NO)
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/mysql_adapter.rb:620:in `real_connect'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/mysql_adapter.rb:620:in`connect'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/mysql_adapter.rb:203:in `initialize'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/mysql_adapter.rb:75:in`new'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/mysql_adapter.rb:75:in `mysql_connection'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:223:in`new_connection'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:245:in `checkout_new_connection'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:188:in`block (2 levels) in checkout'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:184:in `loop'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:184:in`block in checkout'
/usr/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:183:in`checkout'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:98:in `connection'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_pool.rb:326:in`retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_specification.rb:123:in `retrieve_connection'
/var/lib/gems/1.9.1/gems/activerecord-2.3.14/lib/active_record/connection_adapters/abstract/connection_specification.rb:115:in`connection'
/var/www/chiliproject/vendor/plugins/awesome_nested_set/lib/awesome_nested_set.rb:218:in `quoted_left_column_name'
/var/www/chiliproject/vendor/plugins/awesome_nested_set/lib/awesome_nested_set.rb:94:in`acts_as_nested_set'
/var/www/chiliproject/app/models/issue.rb:33:in `<class:Issue>'
/var/www/chiliproject/app/models/issue.rb:15:in`<top (required)>'

**Comment by jdaily** [comment]
Same as issue #79. using RAIL_ENV and git reset --hard a588932639c69ba7736a8b46ff4c683186dab94d fixed issue. Closing as dup.
